### ISSUE TITLE
irq - urban rural exploration with oxford access indicators

### ISSUE THREAD

**Issue by zackarno** [impact-initiatives-geospatial/GeoMSNA2022#8]
@mhkhan27  - since the relationship between FCS/medical costs and distance to nearest water may be driven by rural-urban differences (urban centers closer to rivers), perhaps we should also show some comparison/tests with the oxford indicators (distance to health and urban centers?)

**Comment by mhkhan27** [comment]
Hi Zack thanks for the idea. Added to the script.
